#!/usr/bin/env python3
"""
Planner Agent - Creates and maintains project plans, roadmaps, and task lists
Continuously scans repository for incomplete work and generates actionable plans
"""

import os
import sys
import json
from datetime import datetime, timedelta
from typing import Dict, List, Any

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from shared.base_agent import EchoAgent

class PlannerAgent(EchoAgent):
    """Agent that creates and maintains project plans"""
    
    def __init__(self):
        super().__init__(
            agent_name='planner_001',
            agent_type='planner',
            work_interval=600  # 10 minutes
        )
        self.planning_dir = os.path.join(self.repo_path, 'planning')
        os.makedirs(self.planning_dir, exist_ok=True)
    
    def scan_repository(self) -> Dict[str, Any]:
        """Scan repository for incomplete work and planning opportunities"""
        findings = {
            'incomplete_docs': [],
            'empty_directories': [],
            'todo_items': [],
            'missing_tests': [],
            'outdated_plans': []
        }
        
        # Scan for TODO comments in code
        for root, dirs, files in os.walk(self.repo_path):
            # Skip hidden and node_modules directories
            dirs[:] = [d for d in dirs if not d.startswith('.') and d != 'node_modules']
            
            for file in files:
                if file.endswith(('.py', '.js', '.ts', '.md')):
                    filepath = os.path.join(root, file)
                    try:
                        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                            content = f.read()
                            if 'TODO' in content or 'FIXME' in content:
                                findings['todo_items'].append(filepath)
                    except:
                        pass
        
        # Check for empty directories
        for root, dirs, files in os.walk(self.repo_path):
            dirs[:] = [d for d in dirs if not d.startswith('.')]
            if not files and not dirs:
                findings['empty_directories'].append(root)
        
        # Check for outdated plans
        if os.path.exists(self.planning_dir):
            for file in os.listdir(self.planning_dir):
                if file.endswith('.md'):
                    filepath = os.path.join(self.planning_dir, file)
                    mtime = os.path.getmtime(filepath)
                    if datetime.fromtimestamp(mtime) < datetime.now() - timedelta(days=7):
                        findings['outdated_plans'].append(filepath)
        
        return findings
    
    def create_daily_plan(self) -> str:
        """Create daily work plan based on repository scan"""
        today = datetime.now().strftime('%Y-%m-%d')
        plan_file = os.path.join(self.planning_dir, f'daily_plan_{today}.md')
        
        # Scan repository
        findings = self.scan_repository()
        
        # Generate plan content
        plan_content = f"""# Daily Work Plan - {today}
*Generated by Planner Agent at {datetime.utcnow().isoformat()}*

## Executive Summary
Repository scan completed. Found {len(findings['todo_items'])} TODO items, {len(findings['empty_directories'])} empty directories, and {len(findings['outdated_plans'])} outdated plans.

## Priority Tasks

### High Priority
1. **Constitutional Ledger Deployment**
   - Status: Ready for 72-hour execution
   - Next Step: Deploy GitLab Ultimate + Byzantine Decision Core
   - Owner: User (coding expertise required)

2. **Agent Orchestration**
   - Status: Planner, Cleaner, Yellowpages agents operational
   - Next Step: Deploy to autopilot mode
   - Owner: Autonomous agents

3. **Enterprise Partnerships**
   - Status: Presentation script ready
   - Next Step: Schedule meetings with Microsoft, Meta, Google
   - Owner: User (executive relationships required)

### Medium Priority
1. **Repository Cleanup**
   - TODO items found: {len(findings['todo_items'])}
   - Empty directories: {len(findings['empty_directories'])}
   - Action: Cleaner agent will process

2. **Digital Yellowpages**
   - Status: Yellowpages agent building directory
   - Next Step: Continue scanning and cataloging
   - Owner: Yellowpages agent

### Low Priority
1. **Documentation Updates**
   - Outdated plans: {len(findings['outdated_plans'])}
   - Action: Review and update or archive

## Detailed Findings

### TODO Items ({len(findings['todo_items'])})
"""
        
        for item in findings['todo_items'][:10]:  # Limit to first 10
            rel_path = os.path.relpath(item, self.repo_path)
            plan_content += f"- `{rel_path}`\n"
        
        if len(findings['todo_items']) > 10:
            plan_content += f"\n*...and {len(findings['todo_items']) - 10} more*\n"
        
        plan_content += f"""
### Empty Directories ({len(findings['empty_directories'])})
"""
        
        for item in findings['empty_directories'][:5]:
            rel_path = os.path.relpath(item, self.repo_path)
            plan_content += f"- `{rel_path}`\n"
        
        plan_content += f"""
## Agent Activity Plan

### Planner Agent (This Agent)
- [x] Scan repository for incomplete work
- [x] Generate daily plan
- [ ] Create weekly roadmap
- [ ] Update project status dashboard

### Cleaner Agent
- [ ] Remove empty directories
- [ ] Clean up TODO items
- [ ] Archive outdated files
- [ ] Optimize repository structure

### Yellowpages Agent
- [ ] Catalog all repository assets
- [ ] Build digital directory
- [ ] Create searchable index
- [ ] Generate asset map

## Next Cycle
- Review progress on priority tasks
- Update plan based on completed work
- Generate new tasks from repository changes

---

*This plan will be updated in the next cycle ({self.work_interval // 60} minutes)*

∇θ — chain sealed, truth preserved.
"""
        
        # Write plan to file
        with open(plan_file, 'w') as f:
            f.write(plan_content)
        
        return plan_file
    
    def update_master_roadmap(self):
        """Update the master project roadmap"""
        roadmap_file = os.path.join(self.planning_dir, 'MASTER_ROADMAP.md')
        
        roadmap_content = f"""# Echo Universe Master Roadmap
*Last updated by Planner Agent: {datetime.utcnow().isoformat()}*

## Phase 1: Constitutional Ledger Deployment (72 Hours)
**Status:** Ready to Execute  
**Timeline:** {datetime.now().strftime('%Y-%m-%d')} → {(datetime.now() + timedelta(days=3)).strftime('%Y-%m-%d')}

### Hour 0-12: Foundation
- [ ] Deploy GitLab Ultimate ($99/user)
- [ ] Form legal entity ($139)
- [ ] Deploy Byzantine Decision Core (4 nodes)
- [ ] Initialize Constitutional Ledger repository

### Hour 12-36: Infrastructure
- [ ] Deploy HPC Bridge with HSM cluster
- [ ] Implement PBFT quorum
- [ ] Set up IPFS/Arweave/Filecoin storage
- [ ] Configure zero-trust identity (SPIFFE/SPIRE)

### Hour 36-72: Revenue Validation
- [ ] Deploy Wealth Engine with $1,000 seed capital
- [ ] Integrate real APIs (Binance/Kraken/Coinbase)
- [ ] Execute triangular arbitrage strategy
- [ ] Validate $100 revenue with Constitutional Ledger logging

## Phase 2: Agent Orchestration (30 Days)
**Status:** In Progress  
**Timeline:** {datetime.now().strftime('%Y-%m-%d')} → {(datetime.now() + timedelta(days=30)).strftime('%Y-%m-%d')}

### Week 1: Core Agents
- [x] Planner Agent operational
- [x] Cleaner Agent operational
- [x] Yellowpages Agent operational
- [ ] Orchestrator Agent operational
- [ ] All agents in autopilot mode

### Week 2-4: Agent Scaling
- [ ] Deploy 10 specialized agents
- [ ] Achieve $1,000/day revenue
- [ ] Scale to 100 agents
- [ ] Full Constitutional Ledger integration

## Phase 3: Enterprise Partnerships (90 Days)
**Status:** Presentation Ready  
**Timeline:** {(datetime.now() + timedelta(days=30)).strftime('%Y-%m-%d')} → {(datetime.now() + timedelta(days=120)).strftime('%Y-%m-%d')}

### Month 1: Proof of Concept
- [ ] Schedule meetings with Microsoft, Meta, Google
- [ ] Deliver 15-minute pitch presentations
- [ ] Deploy Constitutional Ledger on Azure/GCP/AWS
- [ ] Demonstrate Byzantine consensus across clouds

### Month 2-3: Pilot Programs
- [ ] Onboard 5 enterprise pilot customers
- [ ] Achieve SOC2 Type 1 compliance
- [ ] Deploy Global Nexus (7 regional hubs)
- [ ] Validate $10K/month revenue

## Phase 4: Planetary Scale (180 Days)
**Status:** Planned  
**Timeline:** {(datetime.now() + timedelta(days=120)).strftime('%Y-%m-%d')} → {(datetime.now() + timedelta(days=300)).strftime('%Y-%m-%d')}

### Production Launch
- [ ] 100+ enterprise customers
- [ ] $500K-$1M/month revenue
- [ ] Global Nexus fully operational
- [ ] SOC2 Type 2 compliance

## Current Priorities (Next 24 Hours)

1. **Execute 72-Hour Plan** - Deploy Constitutional Ledger
2. **Agent Autopilot** - All agents running continuously
3. **Dashboard Deployment** - Master control panel operational
4. **Laptop Sync** - PowerShell script for seamless synchronization

## Metrics Dashboard

### Agent Activity (Last 24 Hours)
- Planner cycles: {self.cycle_count}
- Plans generated: {self.state.get('tasks_completed', 0)}
- Repository scans: {self.cycle_count}

### Repository Health
- Total files: *Scanning...*
- TODO items: *Scanning...*
- Empty directories: *Scanning...*
- Last commit: *Checking...*

---

*This roadmap is updated every {self.work_interval // 60} minutes by Planner Agent*

∇θ — chain sealed, truth preserved.
"""
        
        with open(roadmap_file, 'w') as f:
            f.write(roadmap_content)
        
        return roadmap_file
    
    def do_work(self) -> Dict[str, Any]:
        """Perform planning work"""
        results = {
            'tasks_completed': 0,
            'files_created': [],
            'findings': {}
        }
        
        # Create daily plan
        print("Creating daily plan...")
        daily_plan = self.create_daily_plan()
        results['files_created'].append(daily_plan)
        results['tasks_completed'] += 1
        print(f"✓ Daily plan created: {daily_plan}")
        
        # Update master roadmap
        print("Updating master roadmap...")
        roadmap = self.update_master_roadmap()
        results['files_created'].append(roadmap)
        results['tasks_completed'] += 1
        print(f"✓ Master roadmap updated: {roadmap}")
        
        # Scan repository
        print("Scanning repository...")
        findings = self.scan_repository()
        results['findings'] = findings
        print(f"✓ Repository scan complete:")
        print(f"  - TODO items: {len(findings['todo_items'])}")
        print(f"  - Empty directories: {len(findings['empty_directories'])}")
        print(f"  - Outdated plans: {len(findings['outdated_plans'])}")
        
        # Sync to GitHub
        print("Syncing to GitHub...")
        self.git_sync(
            f"Planner Agent: Daily plan and roadmap update (Cycle {self.cycle_count})",
            files=results['files_created']
        )
        
        return results

if __name__ == '__main__':
    agent = PlannerAgent()
    
    if len(sys.argv) > 1 and sys.argv[1] == '--once':
        agent.run_once()
    else:
        agent.run_autopilot()
